#include "ascii85.hpp"
#include <gtest/gtest.h>
#include <string>
#include <vector>
#include <cstdlib>

// Helper to encode and decode from string
std::string encode(const std::string& input) {
    std::vector<uint8_t> data(input.begin(), input.end());
    return encodeAscii85(data);
}

std::string decode(const std::string& input) {
    std::vector<uint8_t> output = decodeAscii85(input);
    return std::string(output.begin(), output.end());
}

// === Unit Tests ===

// Test case for a known valid encoding ("hello")
TEST(Ascii85Test, EncodeHello) {
    std::string input = "hello";
    std::string expected = "<~BOu!rDZ~>";  // standard ASCII85 for "hello"
    EXPECT_EQ(encode(input), expected);
}

TEST(Ascii85Test, DecodeHello) {
    std::string encoded = "<~BOu!rDZ~>";
    std::string expected = "hello";
    EXPECT_EQ(decode(encoded), expected);
}

TEST(Ascii85Test, RoundTripBasic) {
    std::string input = "Hello Jane!";
    EXPECT_EQ(decode(encode(input)), input);
}

TEST(Ascii85Test, DecodeEmptyString) {
    std::string encoded = "<~>";
    std::string expected = "";
    EXPECT_EQ(decode(encoded), expected);
}

TEST(Ascii85Test, NullByteEncoding) {
    std::string input = std::string("\0\0\0\0", 4);
    std::string encoded = encode(input);
    EXPECT_TRUE(encoded.find('z') != std::string::npos); // 'z' used for 4 null bytes
    EXPECT_EQ(decode(encoded), input);
}

TEST(Ascii85Test, RoundTripWithPadding) {
    std::string input = "abc";  // 3 bytes, will be padded during encoding
    EXPECT_EQ(decode(encode(input)), input);
}

TEST(Ascii85Test, EncodeShortString) {
    std::string input = "ABC";
    std::string encoded = encode(input);
    std::string decoded = decode(encoded);
    EXPECT_EQ(decoded, input);
}

TEST(Ascii85Test, RoundTripSimple) {
    std::string input = "Test123!";
    EXPECT_EQ(decode(encode(input)), input);
}

TEST(Ascii85Test, EncodeNullBlockUsesZ) {
    std::string input = std::string(4, '\0');  // 4 null bytes
    std::string encoded = encode(input);
    EXPECT_NE(encoded.find('z'), std::string::npos);
    EXPECT_EQ(decode(encoded), input);
}

TEST(Ascii85Test, DecodeKnownValue) {
    std::string encoded = "<~BOu!rDZ~>";
    std::string expected = "hello";
    EXPECT_EQ(decode(encoded), expected);
}

// Test case for invalid encoding (invalid characters)
TEST(Ascii85Test, InvalidData) {
    std::string invalid_data = "<~InvalidData~>";  // Invalid ASCII85 encoding
    EXPECT_THROW(decode(invalid_data), std::runtime_error);
}

// Test case for random valid data (you can manually compare the generated string with Python)
TEST(Ascii85Test, RandomValidData) {
    std::string input = "RandomValidData123!";  // Use the random string generated by Python
    std::string encoded = encode(input);  // Encode using your C++ function
    std::string decoded = decode(encoded);  // Decode using your C++ function
    EXPECT_EQ(decoded, input);  // Ensure it matches the original input
}

// Test case for handling invalid input (invalid character outside of ASCII85 range)
// Test case for handling invalid input (invalid character outside of ASCII85 range)
TEST(Ascii85Test, InvalidCharacter) {
    std::string invalid_input = "<~BOu!}rDZ~>";  // '@' is an invalid character in ASCII85
    EXPECT_THROW(decode(invalid_input), std::runtime_error);  // Expect a runtime_error exception
}